version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: |
            mkdir -p .circleci/docker_certs
            cp $DOCKER_CERT_PATH/* .circleci/docker_certs/
            docker build -f .circleci/Dockerfile \
                         -t tomo:$CIRCLE_BUILD_NUM \
                         --build-arg DOCKER_HOST \
                         --build-arg DOCKER_MACHINE_NAME \
                         --build-arg DOCKER_TLS_VERIFY \
                         .
      - run:
          name: bundle exec rake (within docker container)
          command: |
            docker run --name tomo -it tomo:$CIRCLE_BUILD_NUM bundle exec rake

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  cron-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 13 * * 6"
          filters:
            branches:
              only:
                - master
