version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: gem install bundler -v 2.0.1
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rubocop

  test_unit:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: gem install bundler -v 2.0.1
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rake test:unit TESTOPTS="--ci-dir=./reports"
      - store_test_results:
          path: ./reports

  test_docker:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: |
            mkdir -p .circleci/docker_certs
            cp $DOCKER_CERT_PATH/* .circleci/docker_certs/
            docker build -f .circleci/Dockerfile \
                         -t tomo:$CIRCLE_BUILD_NUM \
                         --build-arg DOCKER_HOST \
                         --build-arg DOCKER_MACHINE_NAME \
                         --build-arg DOCKER_TLS_VERIFY \
                         .
      - run:
          name: bundle exec rake test:docker (within docker container)
          command: |
            docker run --name tomo -it tomo:$CIRCLE_BUILD_NUM bundle exec rake test:docker

workflows:
  version: 2
  commit-workflow:
    jobs:
      - rubocop
      - test_docker
      - test_unit
  cron-workflow:
    jobs:
      - rubocop
      - test_docker
      - test_unit
    triggers:
      - schedule:
          cron: "0 13 * * 6"
          filters:
            branches:
              only:
                - master
